"use client"

import { Bar, BarChart, XAxis, YAxis, ResponsiveContainer, Tooltip, Cell } from "recharts"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { agentPerformanceData } from "@/lib/mock-revenue"

export function AgentPerformanceChart() {
  return (
    <Card className="bg-card/50 border-border">
      <CardHeader>
        <CardTitle>Agent Performance</CardTitle>
        <CardDescription>Revenue generated by each agent (last 30 days)</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="h-[300px]">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={agentPerformanceData} layout="vertical" margin={{ top: 0, right: 20, left: 0, bottom: 0 }}>
              <XAxis
                type="number"
                stroke="oklch(0.65 0 0)"
                fontSize={12}
                tickLine={false}
                axisLine={false}
                tickFormatter={(value) => `${value} ETH`}
              />
              <YAxis
                type="category"
                dataKey="name"
                stroke="oklch(0.65 0 0)"
                fontSize={12}
                tickLine={false}
                axisLine={false}
                width={120}
              />
              <Tooltip
                content={({ active, payload }) => {
                  if (active && payload && payload.length) {
                    const data = payload[0].payload
                    return (
                      <div className="rounded-lg border border-border bg-card p-3 shadow-lg">
                        <p className="font-medium">{data.name}</p>
                        <p className="text-sm text-primary">{data.revenue} ETH</p>
                        <p className="text-xs text-muted-foreground">{data.tasks} tasks completed</p>
                      </div>
                    )
                  }
                  return null
                }}
              />
              <Bar dataKey="revenue" radius={[0, 4, 4, 0]}>
                {agentPerformanceData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={`oklch(0.75 0.18 ${195 + index * 30})`} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </CardContent>
    </Card>
  )
}
