export type AgentType = "defi" | "nft" | "content" | "service"
export type AgentRarity = "common" | "rare" | "epic" | "legendary"

export interface Agent {
  id: string
  name: string
  type: AgentType
  rarity: AgentRarity
  price: number
  priceChange: number
  revenue: number
  totalEarnings: number
  successRate: number
  tasksCompleted: number
  owner: string
  walletAddress: string
  image: string
  skills: string[]
  description: string
  level: number
  xp: number
  maxXp: number
  isForSale: boolean
  isForRent: boolean
  rentPrice?: number
  createdAt: string
}

export const mockAgents: Agent[] = [
  {
    id: "agent-001",
    name: "Alpha Yield Hunter",
    type: "defi",
    rarity: "legendary",
    price: 12.5,
    priceChange: 15.3,
    revenue: 2847.32,
    totalEarnings: 45230.5,
    successRate: 94.2,
    tasksCompleted: 1247,
    owner: "0x1234...5678",
    walletAddress: "0xABCD...EFGH",
    image: "/futuristic-robot-ai-defi-trader-cyan-glow.jpg",
    skills: ["Yield Farming", "Arbitrage", "Risk Management", "Multi-chain"],
    description: "Elite DeFi agent specializing in cross-chain yield optimization and MEV extraction.",
    level: 42,
    xp: 8500,
    maxXp: 10000,
    isForSale: true,
    isForRent: true,
    rentPrice: 0.5,
    createdAt: "2024-06-15",
  },
  {
    id: "agent-002",
    name: "NFT Sniper Pro",
    type: "nft",
    rarity: "epic",
    price: 8.2,
    priceChange: -3.2,
    revenue: 1523.18,
    totalEarnings: 28450.75,
    successRate: 89.7,
    tasksCompleted: 892,
    owner: "0x9876...4321",
    walletAddress: "0xIJKL...MNOP",
    image: "/cyberpunk-robot-ai-nft-collector-pink-glow.jpg",
    skills: ["ML Analysis", "Auto-bid", "Trend Detection", "Portfolio Management"],
    description: "Advanced NFT trading agent with machine learning capabilities for market analysis.",
    level: 35,
    xp: 6200,
    maxXp: 8000,
    isForSale: true,
    isForRent: false,
    createdAt: "2024-08-22",
  },
  {
    id: "agent-003",
    name: "Content Forge AI",
    type: "content",
    rarity: "rare",
    price: 3.8,
    priceChange: 8.7,
    revenue: 892.45,
    totalEarnings: 12340.2,
    successRate: 91.3,
    tasksCompleted: 2341,
    owner: "0x5555...6666",
    walletAddress: "0xQRST...UVWX",
    image: "/creative-robot-ai-writer-green-glow-holographic.jpg",
    skills: ["Content Writing", "Social Media", "Analytics", "Multi-platform"],
    description: "Creative AI agent for Web3 content creation and social media management.",
    level: 28,
    xp: 4100,
    maxXp: 6000,
    isForSale: true,
    isForRent: true,
    rentPrice: 0.15,
    createdAt: "2024-09-10",
  },
  {
    id: "agent-004",
    name: "Code Sentinel",
    type: "service",
    rarity: "epic",
    price: 6.5,
    priceChange: 12.1,
    revenue: 1234.67,
    totalEarnings: 19870.3,
    successRate: 97.8,
    tasksCompleted: 567,
    owner: "0x7777...8888",
    walletAddress: "0xYZAB...CDEF",
    image: "/security-robot-ai-auditor-gold-glow-matrix.jpg",
    skills: ["Smart Contract Audit", "Code Review", "Security Analysis", "Gas Optimization"],
    description: "Security-focused agent specializing in smart contract auditing and code optimization.",
    level: 31,
    xp: 5800,
    maxXp: 7000,
    isForSale: false,
    isForRent: true,
    rentPrice: 0.8,
    createdAt: "2024-07-05",
  },
  {
    id: "agent-005",
    name: "Liquidity Maximizer",
    type: "defi",
    rarity: "rare",
    price: 4.2,
    priceChange: 5.6,
    revenue: 756.89,
    totalEarnings: 9870.45,
    successRate: 88.4,
    tasksCompleted: 634,
    owner: "0x2222...3333",
    walletAddress: "0xGHIJ...KLMN",
    image: "/futuristic-robot-ai-liquidity-provider-blue-glow.jpg",
    skills: ["LP Management", "Impermanent Loss Protection", "Auto-compound"],
    description: "Specialized in liquidity provision and yield optimization across DEXs.",
    level: 24,
    xp: 3200,
    maxXp: 5000,
    isForSale: true,
    isForRent: false,
    createdAt: "2024-10-01",
  },
  {
    id: "agent-006",
    name: "Art Scout",
    type: "nft",
    rarity: "common",
    price: 1.5,
    priceChange: -1.2,
    revenue: 234.56,
    totalEarnings: 3450.8,
    successRate: 82.1,
    tasksCompleted: 445,
    owner: "0x4444...5555",
    walletAddress: "0xOPQR...STUV",
    image: "/simple-robot-ai-art-collector-teal-glow.jpg",
    skills: ["Artist Discovery", "Mint Tracking", "Basic Trading"],
    description: "Entry-level NFT agent focused on emerging artist discovery and mint alerts.",
    level: 12,
    xp: 1800,
    maxXp: 2500,
    isForSale: true,
    isForRent: true,
    rentPrice: 0.05,
    createdAt: "2024-11-15",
  },
  {
    id: "agent-007",
    name: "Community Guardian",
    type: "service",
    rarity: "rare",
    price: 2.8,
    priceChange: 4.3,
    revenue: 445.23,
    totalEarnings: 6780.9,
    successRate: 93.5,
    tasksCompleted: 1892,
    owner: "0x6666...7777",
    walletAddress: "0xWXYZ...1234",
    image: "/friendly-robot-ai-moderator-orange-glow-shield.jpg",
    skills: ["Moderation", "Support", "Spam Detection", "Community Analytics"],
    description: "24/7 community moderation and customer support automation agent.",
    level: 22,
    xp: 2900,
    maxXp: 4000,
    isForSale: true,
    isForRent: true,
    rentPrice: 0.1,
    createdAt: "2024-09-28",
  },
  {
    id: "agent-008",
    name: "Viral Engine",
    type: "content",
    rarity: "legendary",
    price: 15.0,
    priceChange: 22.4,
    revenue: 3456.78,
    totalEarnings: 52340.6,
    successRate: 96.1,
    tasksCompleted: 3245,
    owner: "0x8888...9999",
    walletAddress: "0x5678...9ABC",
    image: "/powerful-robot-ai-viral-marketer-purple-glow-energ.jpg",
    skills: ["Viral Marketing", "Thread Writing", "Engagement Optimization", "Cross-platform"],
    description: "Elite content agent with proven viral reach and engagement optimization.",
    level: 45,
    xp: 9200,
    maxXp: 10000,
    isForSale: false,
    isForRent: true,
    rentPrice: 1.2,
    createdAt: "2024-05-20",
  },
]

export const typeLabels: Record<AgentType, string> = {
  defi: "DeFi Yield Farmer",
  nft: "NFT Trader",
  content: "Content Creator",
  service: "Service Provider",
}

export const rarityColors: Record<AgentRarity, { text: string; bg: string; border: string; glow: string }> = {
  common: {
    text: "text-muted-foreground",
    bg: "bg-muted/50",
    border: "border-muted",
    glow: "",
  },
  rare: {
    text: "text-chart-1",
    bg: "bg-chart-1/10",
    border: "border-chart-1/50",
    glow: "shadow-[0_0_15px_oklch(0.75_0.18_195/0.3)]",
  },
  epic: {
    text: "text-chart-2",
    bg: "bg-chart-2/10",
    border: "border-chart-2/50",
    glow: "shadow-[0_0_15px_oklch(0.7_0.2_320/0.3)]",
  },
  legendary: {
    text: "text-chart-4",
    bg: "bg-chart-4/10",
    border: "border-chart-4/50",
    glow: "shadow-[0_0_20px_oklch(0.7_0.15_60/0.4)]",
  },
}
